/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GuiFiles;

import SourceFiles.Main;

/**
 *
 * @author jhw
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        AddStaff = new javax.swing.JButton();
        ManageStaff = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        AddPatient = new javax.swing.JButton();
        ManagePatient = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        AddPayment = new javax.swing.JButton();
        CheckPayment = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        AddTreat = new javax.swing.JButton();
        ManageTreat = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        AddTest = new javax.swing.JButton();
        ManageTest = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        AddAttendance = new javax.swing.JButton();
        CheckAttendance = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        AddWard = new javax.swing.JButton();
        AddUser = new javax.swing.JButton();
        ManageUser = new javax.swing.JButton();
        ManageWard = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("STAFF");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, -1, -1));

        AddStaff.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        AddStaff.setText("Add Staff");
        AddStaff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddStaffActionPerformed(evt);
            }
        });
        jPanel1.add(AddStaff, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, 160, -1));

        ManageStaff.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ManageStaff.setText("Manage Staff");
        ManageStaff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ManageStaffActionPerformed(evt);
            }
        });
        jPanel1.add(ManageStaff, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, 160, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("PATIENT");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 60, -1, -1));

        AddPatient.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        AddPatient.setText("Add Patient");
        AddPatient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddPatientActionPerformed(evt);
            }
        });
        jPanel1.add(AddPatient, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 100, 160, -1));

        ManagePatient.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ManagePatient.setText("Manage Patient");
        ManagePatient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ManagePatientActionPerformed(evt);
            }
        });
        jPanel1.add(ManagePatient, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 150, 160, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("PAYMENT");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 60, -1, -1));

        AddPayment.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        AddPayment.setText("Add Payment");
        AddPayment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddPaymentActionPerformed(evt);
            }
        });
        jPanel1.add(AddPayment, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 100, 160, -1));

        CheckPayment.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        CheckPayment.setText("Manage Payment");
        CheckPayment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckPaymentActionPerformed(evt);
            }
        });
        jPanel1.add(CheckPayment, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 150, 160, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("TREATMENT");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 290, -1, -1));

        AddTreat.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        AddTreat.setText("Add Treatment");
        AddTreat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddTreatActionPerformed(evt);
            }
        });
        jPanel1.add(AddTreat, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 330, 160, -1));

        ManageTreat.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ManageTreat.setText("Manage Treatment");
        ManageTreat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ManageTreatActionPerformed(evt);
            }
        });
        jPanel1.add(ManageTreat, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 380, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("TEST");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 290, -1, -1));

        AddTest.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        AddTest.setText("Add & Search Tests");
        AddTest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddTestActionPerformed(evt);
            }
        });
        jPanel1.add(AddTest, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 330, 220, -1));

        ManageTest.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ManageTest.setText("Manage Tests Undertaken");
        ManageTest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ManageTestActionPerformed(evt);
            }
        });
        jPanel1.add(ManageTest, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 380, 220, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("ATTENDANCE");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 290, -1, -1));

        AddAttendance.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        AddAttendance.setText("Add Attendance");
        AddAttendance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddAttendanceActionPerformed(evt);
            }
        });
        jPanel1.add(AddAttendance, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 330, 160, -1));

        CheckAttendance.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        CheckAttendance.setText("Check Attendance");
        CheckAttendance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckAttendanceActionPerformed(evt);
            }
        });
        jPanel1.add(CheckAttendance, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 380, 160, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("WARD");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 60, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setText("USER");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 290, -1, -1));

        AddWard.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        AddWard.setText("Add Ward");
        AddWard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddWardActionPerformed(evt);
            }
        });
        jPanel1.add(AddWard, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 100, 160, -1));

        AddUser.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        AddUser.setText("Add User");
        AddUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddUserActionPerformed(evt);
            }
        });
        jPanel1.add(AddUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 330, 160, -1));

        ManageUser.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ManageUser.setText("Manage User");
        ManageUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ManageUserActionPerformed(evt);
            }
        });
        jPanel1.add(ManageUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 380, 160, -1));

        ManageWard.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ManageWard.setText("Manage Ward");
        ManageWard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ManageWardActionPerformed(evt);
            }
        });
        jPanel1.add(ManageWard, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 150, 160, -1));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setText("LOG OUT");
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 440, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1018, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 488, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AddStaffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddStaffActionPerformed
        Main.addStaff.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_AddStaffActionPerformed

    private void ManageStaffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ManageStaffActionPerformed
         Main.searchStaff.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_ManageStaffActionPerformed

    private void AddPatientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddPatientActionPerformed
         Main.addPatient.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_AddPatientActionPerformed

    private void ManagePatientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ManagePatientActionPerformed
         Main.searchPatient.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_ManagePatientActionPerformed

    private void AddPaymentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddPaymentActionPerformed
         Main.addBill.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_AddPaymentActionPerformed

    private void CheckPaymentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckPaymentActionPerformed
         Main.searchBill.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_CheckPaymentActionPerformed

    private void AddTreatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddTreatActionPerformed
         Main.addTreatment.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_AddTreatActionPerformed

    private void ManageTreatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ManageTreatActionPerformed
         Main.searchTreatment.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_ManageTreatActionPerformed

    private void AddTestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddTestActionPerformed
         Main.addTest.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_AddTestActionPerformed

    private void ManageTestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ManageTestActionPerformed
         Main.searchTest.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_ManageTestActionPerformed

    private void AddAttendanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddAttendanceActionPerformed
         Main.attendence.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_AddAttendanceActionPerformed

    private void CheckAttendanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckAttendanceActionPerformed
         Main.searchAttendence.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_CheckAttendanceActionPerformed

    private void AddWardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddWardActionPerformed
        Main.addWard.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_AddWardActionPerformed

    private void AddUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddUserActionPerformed
        Main.addUser.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_AddUserActionPerformed

    private void ManageUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ManageUserActionPerformed
        Main.editUser.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_ManageUserActionPerformed

    private void ManageWardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ManageWardActionPerformed
        Main.searchWard.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_ManageWardActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddAttendance;
    private javax.swing.JButton AddPatient;
    private javax.swing.JButton AddPayment;
    private javax.swing.JButton AddStaff;
    private javax.swing.JButton AddTest;
    private javax.swing.JButton AddTreat;
    private javax.swing.JButton AddUser;
    private javax.swing.JButton AddWard;
    private javax.swing.JButton CheckAttendance;
    private javax.swing.JButton CheckPayment;
    private javax.swing.JButton ManagePatient;
    private javax.swing.JButton ManageStaff;
    private javax.swing.JButton ManageTest;
    private javax.swing.JButton ManageTreat;
    private javax.swing.JButton ManageUser;
    private javax.swing.JButton ManageWard;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
