/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GuiFiles;

import SourceFiles.Main;
import SourceFiles.Patient;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;

/**
 *
 * @author jhw
 */
public class SearchPatientFrame extends javax.swing.JFrame {

    /**
     * Creates new form SearchPatientFrame
     */
    public SearchPatientFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtFname = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        rbFemale = new javax.swing.JRadioButton();
        rbMale = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtHome = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtMobile = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtaAddr = new javax.swing.JTextArea();
        jLabel9 = new javax.swing.JLabel();
        txtgrd = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtrel = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        BackButton = new javax.swing.JButton();
        UpdateButton = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        txtLname = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtnic = new javax.swing.JTextField();
        DOB = new com.toedter.calendar.JDateChooser();
        jLabel15 = new javax.swing.JLabel();
        txtPatientid = new javax.swing.JTextField();
        SearchButton = new javax.swing.JButton();
        DOA = new com.toedter.calendar.JDateChooser();
        jLabel16 = new javax.swing.JLabel();
        DOD = new com.toedter.calendar.JDateChooser();
        jLabel17 = new javax.swing.JLabel();
        txtpay = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        txtrec = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        txtcon = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        txtconid = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        txtwardno = new javax.swing.JTextField();
        ClearButton = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        cmbdis = new javax.swing.JComboBox<>();
        lbmsg = new javax.swing.JLabel();
        DeleteButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Patient's Information");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 10, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("First Name");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, -1));
        jPanel1.add(txtFname, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, 220, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Date of Birth");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("Gender");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, -1, -1));

        buttonGroup1.add(rbFemale);
        rbFemale.setText("Female");
        jPanel1.add(rbFemale, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 250, -1, -1));

        buttonGroup1.add(rbMale);
        rbMale.setText("Male");
        rbMale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbMaleActionPerformed(evt);
            }
        });
        jPanel1.add(rbMale, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 250, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("Contact Numbers");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setText("Home");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 310, -1, -1));

        txtHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHomeActionPerformed(evt);
            }
        });
        jPanel1.add(txtHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 310, 170, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setText("Mobile");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 350, -1, -1));

        txtMobile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMobileActionPerformed(evt);
            }
        });
        jPanel1.add(txtMobile, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 350, 170, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel8.setText("Address");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 400, -1, -1));

        txtaAddr.setColumns(20);
        txtaAddr.setRows(5);
        jScrollPane1.setViewportView(txtaAddr);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 390, 230, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel9.setText("Guardian's Name");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 60, -1, -1));
        jPanel1.add(txtgrd, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 60, 210, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel10.setText("Relationship to");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 90, -1, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel11.setText("the Patient");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 100, -1, 20));
        jPanel1.add(txtrel, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 90, 210, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel12.setText("Date of Admission");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 130, -1, 20));

        BackButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        BackButton.setText("BACK");
        BackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButtonActionPerformed(evt);
            }
        });
        jPanel1.add(BackButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 570, -1, -1));

        UpdateButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        UpdateButton.setText("UPDATE");
        UpdateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateButtonActionPerformed(evt);
            }
        });
        jPanel1.add(UpdateButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 570, -1, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel13.setText("Last Name");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, -1, -1));
        jPanel1.add(txtLname, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 170, 220, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel14.setText("NIC");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, -1));
        jPanel1.add(txtnic, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, 220, -1));
        jPanel1.add(DOB, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 210, 220, -1));

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel15.setText("Patient ID");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, -1));
        jPanel1.add(txtPatientid, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 60, 130, -1));

        SearchButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        SearchButton.setText("SEARCH");
        SearchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchButtonActionPerformed(evt);
            }
        });
        jPanel1.add(SearchButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 60, 100, -1));
        jPanel1.add(DOA, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 130, 200, 30));

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel16.setText("Date of discharge");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 170, -1, 20));
        jPanel1.add(DOD, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 170, 200, 30));

        jLabel17.setText("Due Payment");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 220, -1, 20));
        jPanel1.add(txtpay, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 220, 200, 30));

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel18.setText("Recommended By");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 270, -1, 20));

        txtrec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtrecActionPerformed(evt);
            }
        });
        jPanel1.add(txtrec, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 270, 200, 30));

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel19.setText("Confirmed By");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 310, -1, 20));
        jPanel1.add(txtcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 310, 200, 30));

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel20.setText("Consultant's ID");
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 360, -1, 20));
        jPanel1.add(txtconid, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 360, 200, 30));

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel21.setText("Ward No.");
        jPanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 410, -1, 20));
        jPanel1.add(txtwardno, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 400, 200, 30));

        ClearButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ClearButton.setText("CLEAR");
        ClearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearButtonActionPerformed(evt);
            }
        });
        jPanel1.add(ClearButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 570, -1, -1));

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel22.setText("Discharged :");
        jPanel1.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 460, -1, -1));

        cmbdis.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "No", "Yes" }));
        cmbdis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbdisActionPerformed(evt);
            }
        });
        jPanel1.add(cmbdis, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 460, -1, -1));
        jPanel1.add(lbmsg, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, 220, -1));

        DeleteButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        DeleteButton.setText("DELETE");
        DeleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteButtonActionPerformed(evt);
            }
        });
        jPanel1.add(DeleteButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 570, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 751, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 641, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbMaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbMaleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbMaleActionPerformed

    private void txtHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHomeActionPerformed

    private void txtMobileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMobileActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMobileActionPerformed

    private void UpdateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateButtonActionPerformed
        try {
            Patient pat = new Patient(Integer.parseInt(txtPatientid.getText()),Integer.parseInt(txtnic.getText()),txtFname.getText(),txtLname.getText(),String.format("%1$tY-%1$tm-%1$td", DOB.getDate()),txtaAddr.getText(),txtgrd.getText(),txtrel.getText(),String.format("%1$tY-%1$tm-%1$td", DOA.getDate()),String.format("%1$tY-%1$tm-%1$td", DOA.getDate()),Double.parseDouble(txtpay.getText()),cmbdis.getSelectedIndex(),(rbMale.isSelected()?"Male":"Female"),Integer.parseInt(txtHome.getText()),Integer.parseInt(txtMobile.getText()),txtrec.getText(),Integer.parseInt(txtconid.getText()),Integer.parseInt(txtwardno.getText()),Integer.parseInt(txtcon.getText()));
            boolean found = pat.updatePatient();
            if(found==false){
             JOptionPane.showMessageDialog(null,"Error : Patient No. cannot be found");
            }
            else{
                JOptionPane.showMessageDialog(null,"Updated Successfully");
            
            }
        
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_UpdateButtonActionPerformed

    private void txtrecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtrecActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtrecActionPerformed

    private void SearchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchButtonActionPerformed
        try {
            Patient patient = Patient.searchPatient(Integer.parseInt(txtPatientid.getText()));
            if(patient == null){
                JOptionPane.showMessageDialog(null,"Error : Patient Id cannot be found");
            }
            else{
                txtnic.setText(String.valueOf(patient.getNic()));
                txtFname.setText(patient.getFirst_name());
                txtLname.setText(patient.getLast_name());
                DOB.setDate(new SimpleDateFormat("yyyy-mm-dd").parse(patient.getDateOfBirth()));
                if(patient.getGender().equals("Female")){
                    rbFemale.setSelected(true);
                }
                else{rbMale.setSelected(true);}
                
                txtHome.setText(String.valueOf(patient.getContact_home()));
                txtMobile.setText(String.valueOf(patient.getContact_mobile()));
                txtaAddr.setText(patient.getAddress());
                txtgrd.setText(patient.getGuardian());
                txtrel.setText(patient.getRelationship());
                DOA.setDate(new SimpleDateFormat("yyyy-mm-dd").parse(patient.getAdmission_date()));
                DOD.setDate(patient.getDischarge_date()==null?null:new SimpleDateFormat("yyyy-mm-dd").parse(patient.getDischarge_date()));
                txtpay.setText(String.valueOf(patient.getDue_payment()));
                txtrec.setText(patient.getExternal_phy());
                txtcon.setText(String.valueOf(patient.getConfirmation()));
                txtconid.setText(String.valueOf(patient.getConsultant()));
                txtwardno.setText(String.valueOf(patient.getWard_no()));
                cmbdis.setSelectedIndex(patient.getStatus()); //0 specifies the first item
                
                
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_SearchButtonActionPerformed

    private void ClearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearButtonActionPerformed
        txtPatientid.setText("");
        txtnic.setText("");
        txtFname.setText("");
        txtLname.setText("");
        DOB.setDate(null);
        rbFemale.setSelected(false);
        rbMale.setSelected(false);
        txtHome.setText("");
        txtMobile.setText("");
        txtaAddr.setText("");
        txtgrd.setText("");
        txtrel.setText("");
        DOA.setDate(null);
        DOD.setDate(null);
        txtrec.setText("");
        txtcon.setText("");
        txtpay.setText("");
        txtconid.setText("");
        txtwardno.setText("");
        
    }//GEN-LAST:event_ClearButtonActionPerformed

    private void BackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButtonActionPerformed
        Main.mainFrame.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_BackButtonActionPerformed

    private void cmbdisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbdisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbdisActionPerformed

    private void DeleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteButtonActionPerformed
        try {
            boolean found = Patient.deletePatient(Integer.parseInt(txtPatientid.getText()));
            if(found==false){
                JOptionPane.showMessageDialog(null,"Patient ID cannot be found");
            }
            else{
                JOptionPane.showMessageDialog(null,"Deleted Successfully");
            }
            
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_DeleteButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SearchPatientFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SearchPatientFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SearchPatientFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SearchPatientFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SearchPatientFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackButton;
    private javax.swing.JButton ClearButton;
    private com.toedter.calendar.JDateChooser DOA;
    private com.toedter.calendar.JDateChooser DOB;
    private com.toedter.calendar.JDateChooser DOD;
    private javax.swing.JButton DeleteButton;
    private javax.swing.JButton SearchButton;
    private javax.swing.JButton UpdateButton;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cmbdis;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbmsg;
    private javax.swing.JRadioButton rbFemale;
    private javax.swing.JRadioButton rbMale;
    private javax.swing.JTextField txtFname;
    private javax.swing.JTextField txtHome;
    private javax.swing.JTextField txtLname;
    private javax.swing.JTextField txtMobile;
    private javax.swing.JTextField txtPatientid;
    private javax.swing.JTextArea txtaAddr;
    private javax.swing.JTextField txtcon;
    private javax.swing.JTextField txtconid;
    private javax.swing.JTextField txtgrd;
    private javax.swing.JTextField txtnic;
    private javax.swing.JTextField txtpay;
    private javax.swing.JTextField txtrec;
    private javax.swing.JTextField txtrel;
    private javax.swing.JTextField txtwardno;
    // End of variables declaration//GEN-END:variables
}
