/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GuiFiles;

import SourceFiles.Main;
import SourceFiles.Treatment;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;

/**
 *
 * @author jhw
 */
public class SearchTreatment extends javax.swing.JFrame {

    /**
     * Creates new form SearchTreatment
     */
    public SearchTreatment() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Jpanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtPatientId = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtDocId = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtaDscp = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtaResult = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();
        txtPay = new javax.swing.JTextField();
        DeleteButton = new javax.swing.JButton();
        BackButton = new javax.swing.JButton();
        SearchButton = new javax.swing.JButton();
        UpdateButton = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        txtTreatmentid = new javax.swing.JTextField();
        ClearButton = new javax.swing.JButton();
        date = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Jpanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Treatment Details");
        Jpanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Patient's ID");
        Jpanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, -1, -1));
        Jpanel.add(txtPatientId, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, 180, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Doctor's ID");
        Jpanel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, -1, -1));
        Jpanel.add(txtDocId, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 160, 180, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("Date");
        Jpanel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("Description");
        Jpanel.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, -1, -1));

        txtaDscp.setColumns(20);
        txtaDscp.setRows(5);
        jScrollPane1.setViewportView(txtaDscp);

        Jpanel.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 250, 250, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setText("Result of the Treatment");
        Jpanel.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 370, -1, -1));

        txtaResult.setColumns(20);
        txtaResult.setRows(5);
        jScrollPane2.setViewportView(txtaResult);

        Jpanel.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 390, 250, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setText("Payment");
        Jpanel.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 520, -1, -1));
        Jpanel.add(txtPay, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 520, 180, -1));

        DeleteButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        DeleteButton.setText("DELETE");
        DeleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteButtonActionPerformed(evt);
            }
        });
        Jpanel.add(DeleteButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 580, -1, -1));

        BackButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        BackButton.setText("BACK");
        BackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButtonActionPerformed(evt);
            }
        });
        Jpanel.add(BackButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 580, -1, -1));

        SearchButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        SearchButton.setText("SEARCH");
        SearchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchButtonActionPerformed(evt);
            }
        });
        Jpanel.add(SearchButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 50, -1, -1));

        UpdateButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        UpdateButton.setText("UPDATE");
        UpdateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateButtonActionPerformed(evt);
            }
        });
        Jpanel.add(UpdateButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 580, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel8.setText("Treatment ID");
        Jpanel.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, -1));
        Jpanel.add(txtTreatmentid, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, 170, -1));

        ClearButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ClearButton.setText("CLEAR");
        ClearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearButtonActionPerformed(evt);
            }
        });
        Jpanel.add(ClearButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 580, -1, -1));
        Jpanel.add(date, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 210, 180, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Jpanel, javax.swing.GroupLayout.PREFERRED_SIZE, 416, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Jpanel, javax.swing.GroupLayout.PREFERRED_SIZE, 680, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DeleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteButtonActionPerformed
        try {
            boolean found = Treatment.deleteTreatment(Integer.parseInt(txtTreatmentid.getText()));
            if(found==false){
                JOptionPane.showMessageDialog(null,"Error : Treatment ID cannot be found");
                
            }
            else{
                JOptionPane.showMessageDialog(null,"Deleted successfully");
                
            }
            
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_DeleteButtonActionPerformed

    private void SearchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchButtonActionPerformed
        try {
            Treatment trt = Treatment.searchTreatment(Integer.parseInt(txtTreatmentid.getText()));
            if(trt == null){
                JOptionPane.showMessageDialog(null,"Error : Treatment cannot be found");
            }
            else{
                txtPatientId.setText(String.valueOf(trt.getPatientId()));
                txtDocId.setText(String.valueOf(trt.getDocId()));
                date.setDate(new SimpleDateFormat("yyyy-mm-dd").parse(trt.getDate()));
                txtaDscp.setText(trt.getDscp());
                txtaResult.setText(trt.getResult());
                txtPay.setText(String.valueOf(trt.getPayment()));
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_SearchButtonActionPerformed

    private void UpdateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateButtonActionPerformed
       try {
            Treatment trt = new Treatment(Integer.parseInt(txtTreatmentid.getText()),Integer.parseInt(txtPatientId.getText()),Integer.parseInt(txtDocId.getText()),String.format("%1$tY-%1$tm-%1$td",date.getDate()),txtaDscp.getText(),txtaResult.getText(),Double.parseDouble(txtPay.getText()));
            
            boolean found = trt.updateTreatment();
            if(found==false){
             JOptionPane.showMessageDialog(null,"Error : Treatment ID cannot be found");
             
            }
            else{
                JOptionPane.showMessageDialog(null,"Updated Successfully");
                
            }
        
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_UpdateButtonActionPerformed

    private void ClearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearButtonActionPerformed
        txtTreatmentid.setText("");
        txtPatientId.setText("");
        txtDocId.setText("");
        date.setDate(null);
        txtaDscp.setText("");
        txtaResult.setText("");
        txtPay.setText("");
        
    }//GEN-LAST:event_ClearButtonActionPerformed

    private void BackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButtonActionPerformed
        Main.mainFrame.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_BackButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SearchTreatment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SearchTreatment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SearchTreatment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SearchTreatment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SearchTreatment().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackButton;
    private javax.swing.JButton ClearButton;
    private javax.swing.JButton DeleteButton;
    private javax.swing.JPanel Jpanel;
    private javax.swing.JButton SearchButton;
    private javax.swing.JButton UpdateButton;
    private com.toedter.calendar.JDateChooser date;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField txtDocId;
    private javax.swing.JTextField txtPatientId;
    private javax.swing.JTextField txtPay;
    private javax.swing.JTextField txtTreatmentid;
    private javax.swing.JTextArea txtaDscp;
    private javax.swing.JTextArea txtaResult;
    // End of variables declaration//GEN-END:variables
}
